### ISSUE TITLE
Deprecated selector in `focus-light/index.less`

### ISSUE THREAD

**Issue by bookman900** [sindresorhus/atom-focus-light#2]
In `focus-light/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host` => `atom-text-editor`

* `:host .gutter` => `atom-text-editor .gutter`

* `:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line`

* `:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `:host .wrap-guide` => `atom-text-editor .wrap-guide`

* `:host .indent-guide` => `atom-text-editor .indent-guide`

* `:host .invisible-character` => `atom-text-editor .invisible-character`

* `:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region`

* `:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region`

* `:host(.is-focused) .cursor` => `atom-text-editor .cursor`

* `:host(.is-focused) .selection .region` => `atom-text-editor .selection .region`

* `:host(.is-focused) .line-number.cursor-line-no-selection,
:host(.is-focused) .line.cursor-line` => `atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line`

* `.comment,
.constant,
.entity,
.invalid,
.keyword,
.markup,
.meta,
.storage,
.string,
.support,
.variable,
.source,
.link,
.punctuation.definition.begin.gfm,
.punctuation.definition.end.gfm,
.meta.group.braces.tex,
.punctuation.section.group.begin.tex,
.punctuation.section.group.end.tex,
.table.gfm .border.pipe.outer,
.table.gfm .border.pipe.inner,
.table.gfm .border.alignment,
.table.gfm .border.header` => `.syntax--comment,
.syntax--constant,
.syntax--entity,
.syntax--invalid,
.syntax--keyword,
.syntax--markup,
.syntax--meta,
.syntax--storage,
.syntax--string,
.syntax--support,
.syntax--variable,
.syntax--source,
.syntax--link,
.syntax--punctuation.syntax--definition.syntax--begin.syntax--gfm,
.syntax--punctuation.syntax--definition.syntax--end.syntax--gfm,
.syntax--meta.syntax--group.syntax--braces.syntax--tex,
.syntax--punctuation.syntax--section.syntax--group.syntax--begin.syntax--tex,
.syntax--punctuation.syntax--section.syntax--group.syntax--end.syntax--tex,
.syntax--table.syntax--gfm .syntax--border.syntax--pipe.syntax--outer,
.syntax--table.syntax--gfm .syntax--border.syntax--pipe.syntax--inner,
.syntax--table.syntax--gfm .syntax--border.syntax--alignment,
.syntax--table.syntax--gfm .syntax--border.syntax--header`

* `.string.quoted,
.meta.paragraph,
.entity.name.section,
.source.gfm,
.markup.raw.gfm,
.markup.italic.gfm,
.markup.bold.gfm,
.markup.strike.gfm,
.markup.heading,
.comment.quote.gfm,
.entity.gfm,
.comment.line,
.comment.block` => `.syntax--string.syntax--quoted,
.syntax--meta.syntax--paragraph,
.syntax--entity.syntax--name.syntax--section,
.syntax--source.syntax--gfm,
.syntax--markup.syntax--raw.syntax--gfm,
.syntax--markup.syntax--italic.syntax--gfm,
.syntax--markup.syntax--bold.syntax--gfm,
.syntax--markup.syntax--strike.syntax--gfm,
.syntax--markup.syntax--heading,
.syntax--comment.syntax--quote.syntax--gfm,
.syntax--entity.syntax--gfm,
.syntax--comment.line,
.syntax--comment.syntax--block`

* `.markup.underline.link.gfm,
.markup.underline.link.http.hyperlink,
.support.function.general.tex,
.string.other.math.tex,
.string.other.math.block.environment.latex,
.constant.other.general.math.tex,
.meta.group.braces.tex,
.punctuation.definition.string.begin.tex,
.punctuation.definition.string.end.tex,
.punctuation.definition.constant.math.tex,
.string.other.math.tex .punctuation.section.group.begin.tex,
.string.other.math.tex .punctuation.section.group.end.tex,
.string.other.math.block.environment.latex .punctuation.section.group.begin.tex,
.string.other.math.block.environment.latex .punctuation.section.group.end.tex` => `.syntax--markup.syntax--underline.syntax--link.syntax--gfm,
.syntax--markup.syntax--underline.syntax--link.syntax--http.syntax--hyperlink,
.syntax--support.syntax--function.syntax--general.syntax--tex,
.syntax--string.syntax--other.syntax--math.syntax--tex,
.syntax--string.syntax--other.syntax--math.syntax--block.syntax--environment.syntax--latex,
.syntax--constant.syntax--other.syntax--general.syntax--math.syntax--tex,
.syntax--meta.syntax--group.syntax--braces.syntax--tex,
.syntax--punctuation.syntax--definition.syntax--string.syntax--begin.syntax--tex,
.syntax--punctuation.syntax--definition.syntax--string.syntax--end.syntax--tex,
.syntax--punctuation.syntax--definition.syntax--constant.syntax--math.syntax--tex,
.syntax--string.syntax--other.syntax--math.syntax--tex .syntax--punctuation.syntax--section.syntax--group.syntax--begin.syntax--tex,
.syntax--string.syntax--other.syntax--math.syntax--tex .syntax--punctuation.syntax--section.syntax--group.syntax--end.syntax--tex,
.syntax--string.syntax--other.syntax--math.syntax--block.syntax--environment.syntax--latex .syntax--punctuation.syntax--section.syntax--group.syntax--begin.syntax--tex,
.syntax--string.syntax--other.syntax--math.syntax--block.syntax--environment.syntax--latex .syntax--punctuation.syntax--section.syntax--group.syntax--end.syntax--tex`

* `.string.quoted.double.html,
.string.quoted.double.xml,
.markup.heading.marker.gfm,
.variable.parameter.function.latex,
.punctuation.definition.arguments.begin.latex,
.punctuation.definition.arguments.end.latex` => `.syntax--string.syntax--quoted.syntax--double.syntax--html,
.syntax--string.syntax--quoted.syntax--double.syntax--xml,
.syntax--markup.syntax--heading.syntax--marker.syntax--gfm,
.syntax--variable.syntax--parameter.syntax--function.syntax--latex,
.syntax--punctuation.syntax--definition.syntax--arguments.syntax--begin.syntax--latex,
.syntax--punctuation.syntax--definition.syntax--arguments.syntax--end.syntax--latex`

* `.markup.italic.gfm` => `.syntax--markup.syntax--italic.syntax--gfm`

* `.markup.bold.gfm,
.markup.heading.heading-1.gfm,
.markup.heading.heading-2.gfm,
.markup.heading.heading-3.gfm,
.markup.heading.heading-4.gfm,
.markup.heading.heading-5.gfm,
.markup.heading.heading-6.gfm` => `.syntax--markup.syntax--bold.syntax--gfm,
.syntax--markup.syntax--heading.syntax--heading-1.syntax--gfm,
.syntax--markup.syntax--heading.syntax--heading-2.syntax--gfm,
.syntax--markup.syntax--heading.syntax--heading-3.syntax--gfm,
.syntax--markup.syntax--heading.syntax--heading-4.syntax--gfm,
.syntax--markup.syntax--heading.syntax--heading-5.syntax--gfm,
.syntax--markup.syntax--heading.syntax--heading-6.syntax--gfm`

* `.markup.strike.gfm` => `.syntax--markup.syntax--strike.syntax--gfm`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by nlfonseca** [comment]
Hello, I'm picking this up. I already update the index.less.
